AWSTemplateFormatVersion: '2010-09-09'
Description: Apis generator test
Resources:
  RoleTest: 
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: apis-generator-role-test
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
  FunctionTest:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName : depositos-bancarios-api-account-credit-http-post-todo
      Runtime: nodejs14.x
      Role: !GetAtt 'RoleTest.Arn'
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async (event) => {
              const response = {
                  statusCode: 200,
                  body: JSON.stringify('Successful transaction'),
              };
              return response;
          };
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: depositos-bancarios-api-account-credit-http-delete-todo
      DefinitionString: |-
        {
          "Comment": "A description of my state machine",
          "StartAt": "Wait",
          "States": {
            "Wait": {
              "Type": "Wait",
              "Seconds": 9,
              "End": true
            }
          }
        }
      RoleArn: !GetAtt 'RoleTest.Arn'